# -*- coding: utf-8 -*-
"""
Created on Sat May  5 14:13:24 2018

@author: Gaurav Roy
"""
def add_stopwords():
    stopwordsList = []
    stopwordsList.append('say')
    stopwordsList.append('said')
    stopwordsList.append('saying')
    stopwordsList.append('one')
    stopwordsList.append('the')
    stopwordsList.append('go')
    stopwordsList.append('going')
    stopwordsList.append('gone')
    stopwordsList.append('and')
    stopwordsList.append('hear')
    stopwordsList.append('look')
    stopwordsList.append('looking')
    stopwordsList.append('looked')
    stopwordsList.append('saw')
    stopwordsList.append('see')
    stopwordsList.append('seeing')
    stopwordsList.append('seen')
    stopwordsList.append('seem')
    stopwordsList.append('seemed')
    stopwordsList.append('seemingly')
    stopwordsList.append('whether')
    stopwordsList.append('along')
    stopwordsList.append('come')
    stopwordsList.append('coming')
    stopwordsList.append('came')
    stopwordsList.append('get')
    stopwordsList.append('got')
    stopwordsList.append('getting')
    stopwordsList.append('show')
    stopwordsList.append('showing')
    stopwordsList.append('showed')
    stopwordsList.append('yet')
    stopwordsList.append('till')
    stopwordsList.append('else')
    stopwordsList.append('especially')
    stopwordsList.append('something')
    stopwordsList.append('but')
    stopwordsList.append('like')
    stopwordsList.append('others')
    stopwordsList.append('new')
    stopwordsList.append('without')
    stopwordsList.append('would')
    stopwordsList.append('they')
    stopwordsList.append('when')
    stopwordsList.append('always')
    stopwordsList.append('really')
    stopwordsList.append('around')
    stopwordsList.append('oh')
    stopwordsList.append('there')
    stopwordsList.append('if')
    stopwordsList.append('never')
    stopwordsList.append('suddenly')
    stopwordsList.append('in')
    stopwordsList.append('on')
    stopwordsList.append('cannot')
    stopwordsList.append('also')
    stopwordsList.append('want')
    stopwordsList.append('wanted')
    stopwordsList.append('quite')
    stopwordsList.append('much')
    
    return stopwordsList
    
